main: com.etwxr9.dfmc.Main
version: "beta0.5"
author: etwxr9
name: DFMC
api-version: 1.16
depend: []
softdepend: [FastAsyncWorldEdit]
commands:
  dfmc:
     description: DFMC commands
     default: op